import 'package:chit/modules/chit/models/chit.dart';
import 'package:chit/services/shared_pref_services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class ChitViewModel extends StateNotifier<List<Chit>> {
  ChitViewModel() : super([]) {
    initCounter();
  }

  static int autoGeneratedId = 0;

  Future<void> initCounter() async {
    autoGeneratedId = await SharedPrefsService.getChitCounter();
  }

  Future<void> addChit(String customerName, String phoneNumber) async {
    autoGeneratedId++;
    final newChit = Chit(
      id: autoGeneratedId,
      customerName: customerName,
      customerMobileNumber: phoneNumber,
    );

    state = [...state, newChit];

    await SharedPrefsService.saveChitCounter(autoGeneratedId);
  }
}
